package com.example.aziz;

public class App {
    public static void main(String[] args) throws Exception {
        //System.out.println("Hello, World!");
        //Permutation.permutation("123");
        //Permutation.test();
        //AryTest.runTest();
        //AryIterate.runTest();
        //AryInsert.runTest();
        //AryUpdate.runTest();
        //AryRetrieve.runTest();
        //AryRemove.runTest();
        //ArySearch.runTest();
        //ArySort.runTest();
        //AryCopy.runTest();
        //AryShuffle.runTest();
        //AryReverse.runTest();
        //AryExtract.runTest();
        //AryCompareList.runTest();
        //ArySwap.runTest();
        //AryCombine.runTest();
        //AryClone.runTest();
        //AryEmpty.runTest();
        //AryTestEmpty.runTest();
        //AryTrim.runTest();
        //AryIncrease.runTest();
        //AryReplace.runTest();
        //LinkedAppend.runTest();
        //LinkedIterate.runTest();
        //LinkedIterate2.runTest();
        //LinkedReverse.runTest();
        //HackerRankScanner.runTest();
        //HackerRankPrintf.runTest();
        //HackerRankLoop2.runTest();
        //HackerRankFile.runTest();
        //HackerRankException.runTest();
        //HackerRankConvert.runTest();
        //HackerRankDateTime.runTest();
        //HackerRankCurrencyFormatter.runTest();
        //HackerRankSingleton.runTest();
        //HackerRankTreeQuestion.runTest();
        //HackerRankSubstringCompare.runTest();
        //HackerRankPalindrome.runTest();
        //HackerRankAnagram.runTest();
        //HackerRankStringPattern.runTest();
        //Linked5InsertSpecified.runTest();
        // Linked6InsertFirstLast.runTest();
        // Linked7Insertelementfront.runTest();
        // Linked8Insertelemetend.runTest();
        // Linked9somelelements.runTest();
        // Linked10firstlastoccurance.runTest();
        // Linked11displayelemets.runTest();
        // Linked12RemoveElement.runTest();
        // Linked13RemoveFirstLast.runTest();
        // Linked14RemoveAll.runTest();
        // Linked15SwapTwo.runTest();
        // Linked16ShuffleElements.runTest();
        // Linked17JoinTwoLinked.runTest();
        // Linked18CloneList.runTest();
        // Linked19RemoveAndReturn.runTest();
        // Linked20RetreiveNotRemove.runTest();
        //Linked21RetreiveNotRemoveLast.runTest();
        // Linked22CheckParticularElementExist.runTest();
        // Linked23LinkedToArray.runTest();
        // Linked24CompareTwoLinked.runTest();
        // Linked25TestNotEmpty.runTest();
        // Linked26ReplaceElement.runTest();
        // Hashset1AppendElement.runTest();
        // Hashset2IterateElements.runTest();
        // Hashset3GetNumberElements.runTest();
        // Hashset4EmptyHashset.runTest();
        // Hashset5TestEmpty.runTest();
        // Hashset6CloneToAnother.runTest();
        // Hashset7ConvertToArray.runTest();
        // Hashset8HashsetToTreeset.runTest();
        // Hashset9HashsetToList.runTest();
        // Hashset10CompareTwo.runTest();
        // Hashset11CompareRetainElement.runTest();
        // Hashset12RemoveElements.runTest();
        // Treeset1Create.runTest();
        // Treeset2Iterate.runTest();
        // Treeset3AddElemets.runTest();
        // Treeset4ReverseOrder.runTest();
        // Treeset5FirstLast.runTest();
        // Treeset6Clome.rumTest();
        // Treeset7MumberofElememts.rumTest();
        // Treeset8CompareTwo.rumTest();
        // Treeset9Fimdmumber.rumTest();
        // Treeset10GetElememtGreater.rumTest();
        // Treeset11GetElememtsLess.rumTest();
        //Treeset12StricklyGreater.rumTest();
        // Treeset13Strictlyless.runTest();
        // Treeset14RetreiveWhileRemove.runTest();
        // Treeset15RetrieveWhileRemove.runTest();
        // PriorityQueue1Create.runTest();
        // PriorityQueue2Iterate.runTest();
        // PriorityQueue3AddToAnother.runTest();
        // Priority4InsertGivenElement.runTest();
        // PriorityQueue5RemoveAllElements.runTest();
        // PriorityQueue7CompareTwo.runTest();
        // PriorityQueue8RetrieveFirstElement.runTest();
        // PriorityQueue9RetreiveAndRemove.runTest();
        // PriorityQueue10ToArray.runTest();
        // PriorityQueue11ToElementString.runTest();
        // PriorityQueue12ToMaximum.rumTest();
        // Hashmap1Associate.runTest();
        // Hashmap2CountSize.runTest();
        // Hashmap3CopyMappings.runTest();
        // Hashmap4RemoveMappings.runTest();
        // Hashmap5WeitherContains.runTest();
        // Hashmap6ShallowCopy.runTest();
        // Hashmap7TestContainsKey.runTest();
        // Hashmap8ContainsValue.runTest();
        // HAshmap9CreateSetview.runTest();
        // Hashmap10GetValue.runTest();
        // Hashmap11SetviewOfKeys.runTest();
        // Hashmap12CollectionviewOfValues.runTest();
        // Treemap1AssociateKeyValue.rumTest();
        // Treemap2CopyToAnother.runTest();
        // Treemap3SearchAKey.runTest();
        // Treemap4SearchValue.runTest();
        // Treemap5GetAllKey.runTest();
        // Treemap6DeleteAll.runTest();
        // Treemap7SortKeys.runTest();
        // Treemap8GetKeyValueMapping.runTest();
        // Treemap9GetFirstAndLast.runTest();
        // Treemap10ReverseOrder.runTest();
        // Treemap11LessEqualto.runTest();
        // Treemap12GreatestLessThanEqual.runTest();
        // Treemap13PortionStriclyLess.runTest();
        // Treemap14PortionLess.runTest();
        Treemap15PortionStrictlyLess.runTest();
    }
}
